# Generated by Django 5.2.17 on 2026-09-21 21:13

import acom.domain.estados
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadComplementaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            (
                                "investigacion",
                                "Proyectos de investigación y desarrollo tecnológico",
                            ),
                            ("curso", "Cursos, talleres y diplomados"),
                            ("publicacion", "Publicaciones y ponencias"),
                            (
                                "cultural_deportiva",
                                "Actividades culturales y deportivas",
                            ),
                            ("tutoria", "Tutorías y asesorías"),
                            (
                                "impacto_social",
                                "Proyectos de impacto social y ambiente",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("creditos_valor", models.DecimalField(decimal_places=2, max_digits=4)),
                ("activa", models.BooleanField(default=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("inscrito", "Inscrito"),
                            ("evaluado_aprobado", "Evaluado — aprobado"),
                            ("evaluado_rechazado", "Evaluado — rechazado"),
                            ("constancia_emitida", "Constancia emitida"),
                            ("validado", "Validado (créditos registrados)"),
                        ],
                        default=acom.domain.estados.EstadoInscripcion["INSCRITO"],
                        max_length=20,
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                ("fecha_evaluacion", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="acom.actividadcomplementaria",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_acom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "can_validate_credits",
                        "Puede validar constancias y registrar créditos",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Constancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=30, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "emitida_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constancia",
                        to="acom.inscripcion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroCreditos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creditos_otorgados",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_creditos",
                        to="acom.inscripcion",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="actividadcomplementaria",
            constraint=models.CheckConstraint(
                condition=models.Q(("creditos_valor__gt", 0)),
                name="actividad_creditos_positivos",
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcion",
            index=models.Index(
                fields=["estudiante", "estado"], name="acom_inscri_estudia_9cfc47_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "actividad"),
                name="uniq_inscripcion_por_actividad",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrocreditos",
            constraint=models.CheckConstraint(
                condition=models.Q(("creditos_otorgados__gt", 0)),
                name="registro_creditos_positivos",
            ),
        ),
    ]
